# -*- coding: utf-8 -*-
"""Cs104 general

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uClfPTIPs9PJKD4YqEZPCOcZ1TUHBXaR

# 8 / 31  Lecture
"""

#boolean type
age = int(input("How old are you? "))
senior = age >= 65
print(senior)

#score grader
grade = int(input("input score "))
letter_grade = "error"
if grade >= 90:
  letter_grade = "A"
elif grade >= 80:
  letter_grade = "B"
elif grade >= 70:
  letter_grade = "C"
elif grade >= 60:
  letter_grade = "D"
else:
  letter_grade = "F"
print("letter grade: "+ letter_grade)

#while loop version
count = 0
sum = 0

def check_int(x):
  try:
    int(x)
    return(True)
  except:
    return(False)

while count < 2:
  grade = input("input score ")
  letter_grade = "error"
  if check_int(grade) == False:
    print("please only input numbers")
    continue
  elif int(grade) <= 0:
    print("no negative numbers")
    continue
  elif int(grade) >= 90:
    letter_grade = "A"
    count+=1
  elif int(grade) >= 80:
    letter_grade = "B"
    count+=1
  elif int(grade) >= 70:
    letter_grade = "C"
    count+=1
  elif int(grade) >= 60:
    letter_grade = "D"
    count+=1
  else:
    letter_grade = "F"
    count+=1
  sum += int(grade)
  print("letter grade: "+ letter_grade)

average = sum/count

print(f"The average is: {average:.2f}")

#other if statement fun
a = input("Boo! ")
a = a.lower()
if a[:3] == "ahh":
  print("gotcha")
elif a[:4] == "what":
  print("aww")
else:
  print("what?")

#this was on the board
a = "C"
a = a.lower()
print(a)