# -*- coding: utf-8 -*-
"""Cs104 lab 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GH_0vbYzi8lpwKEIS0tIoXjUmU5qsuwN
"""

#get a number from the user
num0 = int(input("Give a number greater than 20: "))

#turn the input into a binary and hex representation, this is done here for easier manipulation in the output
test1 = str(bin(num0))
test2 = str(hex(num0))

#output both conversions in a nice, easy-to-read format (removing prefix)
print(str(num0) + " in binary is " + test1[2:])
print(", in hex it is " + test2[2:])

#convert both back into base-10
print("just to check...")

print(int(test1,2))
print(int(test2,16))

num_1= 10
num_2 = 11.0
course_code = "cs104"
course_name = "Intro CS Using Python"
my_name= "Patrick Etheredge"

#print variable types
print(type(num_1))
print(type(num_2))
print(type(my_name))

#calculate and print num_4
num_4 = num_1 * num_2
print(num_4)

# calculate and print num_5, then print the integer part of num_5 and the
# modular remainder of num_2 / num_1. and then also the decimal remainder
# because im not sure which I should do.
num_5 = num_2 / num_1
print(num_5)
print(num_2 // num_1)
print(num_2 % num_1)
print(num_5 - (num_2 // num_1))

#final bit
print(my_name + " is taking " + course_name)

