# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KK8rm2m5O5wHDNdc5tIhvxzBOKvlAzyX
"""

# to be used later, for easier reading
def letter_grade(x):
  if x >= 90:
    return("A")
  elif x >= 80:
    return("B")
  elif x >= 70:
    return("C")
  elif x >= 60:
    return("D")
  elif x >= 0:
    return("f")
  else:
    return("error, negative or non-existant score")

#create file
with open("grade_report.txt", "w") as txt:

  #define variables
  go = 1
  sum = 0
  count = 0

  # making it a while loop which can be exited at any time makes the user experience much better
  while go == 1:
    name = input("Give Student Name or type 'Q' to exit ")

    # quit functionality
    if name == "Q":
      go = 0
      continue

    # boilerplate
    score = input(name + "'s score: ")
    sum += float(score)
    count += 1

    # write primary grade table
    txt.write(f"{name:40} {float(score):.2f}\n")

  #calculate average
  average = sum/count

  # write footer information
  txt.write("\n")
  txt.write(f"Class Average   {average:.2f}\n")
  txt.write(f"Grade:              {letter_grade(average)}")