# -*- coding: utf-8 -*-
"""Lab 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rN3-trfe0o0Nvqp8MoW6ceMSpw7y39_
"""

# to be used later, for easier reading
def letter_grade(x):
  if x >= 90:
    return("A")
  elif x >= 80:
    return("B")
  elif x >= 70:
    return("C")
  elif x >= 60:
    return("D")
  elif x >= 0:
    return("F")
  else:
    return("error, negative score")


#create file
with open("grade_report.txt", "w") as txt:

  #define variables
  go = 1
  sum = 0
  count = 0

  # making it a while loop which can be exited at any time makes the user experience much better
  while go == 1:
    name = input("Give Student Name or type 'Q' to exit ")

    # quit/end functionality that checks for student count and warns the user
    if name == "Q" and count >= 5:
      go = 0
      continue
    elif name == "Q" and input("You have less than 5 students in the form, are you sure you want to quit? Y/N  ") == "Y":
      go = 0
      continue
    elif name == "Q":  # this handles if the user wants to continue (answer was not "Y")
      name = ""
      print("Continuing...")
      continue

    # boilerplate incrementing, but the while loop checks to see if the inputted number is actually a number
    go2 = 1
    while go2 == 1:
      score = input(name + "'s score: ")
      try:
        sum += float(score)
      except:
        print("please only input a number. decimals are fine")
        continue
      go2 = 0
    count += 1

    # write primary grade table, now with individual letter grades
    txt.write(f"{name:30} {float(score):10.2f} {letter_grade(float(score))}\n")

  #calculate average
  average = sum/count

  # write footer information
  txt.write("\n")
  txt.write(f"Class Average   {average:.2f}\n")
  txt.write(f"Grade                {letter_grade(average)}")